FROM ubuntu:22.04
ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get update && apt-get install -y \
    apache2 \
    php \
    libapache2-mod-php \
    git \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*
RUN rm -rf /var/www/html/* && \
    git clone https://github.com/banago/simple-php-website.git /var/www/html/
RUN chown -R www-data:www-data /var/www/html/

EXPOSE 80

CMD ["apache2ctl", "-D", "FOREGROUND"]

